services:
  app:
    # image: public.ecr.aws/docker/library/php:8.1-fpm
    image: docker.io/wachiradu/php:8.2.7-fpm-foodking-v3
    container_name: app
    restart: unless-stopped
    environment:
      TZ: "Asia/Bangkok"
    working_dir: /var/www
    volumes:
      - ./site-app/:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - laravel

  web:
    image: public.ecr.aws/nginx/nginx:1.27.0
    container_name: web
    restart: unless-stopped
    environment:
      TZ: "Asia/Bangkok"    
    depends_on:
      - app
    ports:
      - "8082:80"
    volumes:
      - ./site-app/:/var/www
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel

  db:
    image: public.ecr.aws/docker/library/mysql:8.0.38
    container_name: db
    restart: unless-stopped
    environment:
      TZ: "Asia/Bangkok"
      MYSQL_ROOT_PASSWORD: example1234
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - ./db_data/:/var/lib/mysql
    networks:
      - laravel

  phpmyadmin:
    image: docker.io/library/phpmyadmin:5.2.1-apache
    container_name: phpmyadmin
    restart: unless-stopped
    ports:
      - "8083:80"
    environment:
      TZ: "Asia/Bangkok"
      MYSQL_ROOT_PASSWORD: example1234
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    depends_on:
      - db
    networks:
      - laravel


networks:
  laravel:
    driver: bridge
